### ISSUE TITLE
Flash Button shows up as "B...n"

### ISSUE THREAD

**Issue by waterskier2007** [ytakzk/Fusuma#10]
Is there a missing resource? It doesn't seem that there is

**Comment by aslisabanci** [comment]
Hello, I'm using v0.2.3 and I wanted to report the same problem. This is not a issue on the simulator but on my device - iPhone 6p. Also strangely, when I run the example project on my device it's OK. But when I run my own project with the pod, it's buggy.
You can let me know if you require extra information from my side that can be helpful. Cheers and thanks for sharing this library!

**Comment by ytakzk** [comment]
@aslisabanci How about 0.2.4? I just updated the podspec and you can install the latest version now.

**Comment by aslisabanci** [comment]
@ytakzk Awesome, v0.2.4 fixed it :) 
Thanks again for sharing this, cheers!
