### ISSUE TITLE
Does not crop image

### ISSUE THREAD

**Issue by shripadkulkarnid** [ytakzk/Fusuma#105]
I use this pod and change the method  true to  crop image but this does not give me output please guide

**Comment by masbenx** [comment]
same here, when i use 0.6.0 with swift 2.3 after chose or take image from camera and library, the crop view doesn't show

**Comment by shripadkulkarnid** [comment]
use fusuma pod only for taking image from gallery , camera . for image crop , use MMSCropView pod
