### ISSUE TITLE
Audio not coming when i record video

### ISSUE THREAD

**Issue by AmmySingh** [ytakzk/Fusuma#106]
I'm trying to record the video and after record when i play this then audio is not coming. Can anyone tell me what is the problem here.

**Comment by cresouls** [comment]
in FSVideoCameraView.swift , add the following code in functions initialize and flipbuttonpressed

```
for device in AVCaptureDevice.devicesWithMediaType(AVMediaTypeAudio) {
                    let device = device as? AVCaptureDevice
                    var audioInput = try! AVCaptureDeviceInput(device: device)
                    session.addInput(audioInput)
                }
```

**Comment by AmmySingh** [comment]
@cresouls It works with your code, Thanks for help. GBU. 👍

**Comment by cresouls** [comment]
no problem :)

**Comment by ytakzk** [comment]
@AmmySingh Solved 👍
