### ISSUE TITLE
Delegate error

### ISSUE THREAD

**Issue by mareksDev** [ytakzk/Fusuma#107]
With swift 3 i get error Type "ViewController" does not conform to protocol "FusumaDelegate"

What might be the issue?

in my button i initialize fusumaViewController and then try to assign the delegate to self.

**Comment by andreyrd** [comment]
I didn't have this issue until the latest version (1.0.1), but it looks like

```
public protocol FusumaDelegate: class {
    // MARK: Required
    func fusumaImageSelected(_ image: UIImage, source: FusumaMode)
    func fusumaVideoCompleted(withFileURL fileURL: URL)
    func fusumaCameraRollUnauthorized()
 
    // MARK: Optional
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode)
    func fusumaClosed()
}

extension FusumaDelegate {
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode) {}
    func fusumaClosed() {}
}
```

needs to become

```
public protocol FusumaDelegate: class {
    // MARK: Required
    func fusumaImageSelected(_ image: UIImage, source: FusumaMode)
    func fusumaVideoCompleted(withFileURL fileURL: URL)
    func fusumaCameraRollUnauthorized()
 
    // MARK: Optional
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode)
    func fusumaClosed()
}

public extension FusumaDelegate {
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode) {}
    func fusumaClosed() {}
}
```

because the implementation of `fusumaDismissedWithImage` and `fusumaClosed` isn't seen outside of the library source, so Swift requires that the user implement those functions, which are supposed to be optional.

**Comment by andreyrd** [comment]
Sorry, it looks like this is actually an unrelated issue, introduced with 557c607dc6cf940edfdb17c690406618e23ff04f
Opened issue #131
