### ISSUE TITLE
Can we show just only camera? 

### ISSUE THREAD

**Issue by ibhupi** [ytakzk/Fusuma#109]
I just want camera only, not camera roll  or albums.

**Comment by meirinberg** [comment]
Same here, did you find your solution?

**Comment by ibhupi** [comment]
No, though I decided to let user select existing images in my project.

**Comment by gali8** [comment]
You can do that, using extensions.

extension FusumaViewController {

    func hideButtons() {
        let btnLibrary = self.valueForKey("libraryButton") as? UIButton
        let btnCamera = self.valueForKey("cameraButton") as? UIButton
        
        btnLibrary?.hidden = true
        btnCamera?.hidden = true
    }
}

After the FusumaViewController presentation call fusumaPicker.hideButtons()

Don't forget to add, before the presentation, these two lines if you wanna just the camera:
  fusumaPicker.modeOrder = .CameraFirst
  fusumaPicker.defaultMode = .Camera

**Comment by ytakzk** [comment]
@gali8 Could you give me the PR? That would be helpful for the users 🙇

**Comment by ytakzk** [comment]
#108
