### ISSUE TITLE
Constraints are broken...

### ISSUE THREAD

**Issue by meirinberg** [ytakzk/Fusuma#110]
I love this project, but I am having some interface issues. After the default device option shows in the .xib files, the constraints break. I have tried to change the constraints but it only leads to more errors and bugs. Can someone add new/correct .xib files to this project? Any help would be appreciated.

**Comment by Viktormax** [comment]
I'm afraid i've the same issue:

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Fusuma.FSCameraView 0x7f85d6525230> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key croppedAspectRatioConstraint.'
