### ISSUE TITLE
Checkmark is not visible after first-time authorization

### ISSUE THREAD

**Issue by dkcas11** [ytakzk/Fusuma#112]
Hey, for some reason the checkmark to confirm your image selection is not visible after authorization to use the photo library/camera.

Also, any way to disable the disabling of the status bar? I think it may be the cause to messing with my collection view, but i'd like to disable it anyway :)

Thanks.

**Comment by alexanderlipsett** [comment]
Hey, I have this issue as well. I think its related to the UIAlertController that asks for photos permissions - I've only noticed the issue when it presents. A fix for the time being is simply to ask for photo permissions before presenting Fusuma. I tried this and it seems like it resolves the issue.

**Comment by claygarrett** [comment]
Fixed this here: https://github.com/ytakzk/Fusuma/pull/116

**Comment by dkcas11** [comment]
Awesome :)

For my second question/problem, for anyone wondering, the UICollectionView automatically sets it's offset to 0, hence the skewed offset. Solved it by setting the offset to the current one through viewDidDisappear, with no animation so it won't be noticed :)
