### ISSUE TITLE
Album starts dragging up when I want to crop image

### ISSUE THREAD

**Issue by thyselius** [ytakzk/Fusuma#114]
Thanks for a great project!

In album view

After having dragged the album up once to reveal more images and then selected one, pinching to zoom/crop and panning the loaded image with one or two fingers would start the dragging up of the album, but the intended action is rather to pinch to zoom or pan the crop view.

Adding a class variable solved this issue

```
var canPanDuringThisTouch = true
```

Then add the line to the panned() function 

```
    if sender.state == .Began {

        let view    = sender.view
        let loc     = sender.locationInView(view)
        let subview = view?.hitTest(loc, withEvent: nil)

        if subview == imageCropView && imageCropViewConstraintTop.constant == imageCropViewOriginalConstraintTop {
            // if the pan starts in the image field, don't let this touch start dragging the album, since it's a crop gesture
            canPanDuringThisTouch = false
            return
        }
```

and in the last } else { , add:

```
        canPanDuringThisTouch = true // reset this value for the next interaction
```

**Comment by dalu93** [comment]
@thyselius what about creating a PR? If you don't have time, I'll do it :)

**Comment by thyselius** [comment]
I made some other changes too so I won't do it right now. Should be incorporated by author since it's a bug, but go ahead and create a pr sounds good!

**Comment by Zehua-LIN** [comment]
@thyselius Hi, I'm having the same issue. I don't see anywhere in your answer that you are checking the bool value to stop album from dragging up, how do you make that happen?

**Comment by thyselius** [comment]
Hi, saw this comment now, sorry for the late reply

In the function panned(sender: UITapGestureRecognizer)


		...
		} else if sender.state == .Changed {
			
			if canPanDuringThisTouch == false {
				return
			}
            
			let currentPos = sender.locationInView(self)

		...

**Comment by Zehua-LIN** [comment]
@thyselius thank you so much!
