### ISSUE TITLE
Branch Swift 2.2

### ISSUE THREAD

**Issue by SebastienGracia** [ytakzk/Fusuma#115]
Hello,

is it possible to have a branch Swift 2.2 to work with project Xcode 7.3.1 ?

Ty

**Comment by ytakzk** [comment]
@SebastienGracia do you still need swift2.2 support?

**Comment by SebastienGracia** [comment]
it's ok i resolve it 

regards

**Comment by ytakzk** [comment]
@SebastienGracia ok. let me close this issue.
