### ISSUE TITLE
Wrong image orientation when device Orientation Lock is on

### ISSUE THREAD

**Issue by mamouneyya** [ytakzk/Fusuma#121]
When the device Orientation Lock is on, the logic in FSCameraView # 187 won't work since it will always set the image orientation to the locked one.

I'm still fighting with this to get it right. Will create a PR if I came into something work. Until then I would appreciate any advice and/or hint...

**Comment by mamouneyya** [comment]
I've ended up using `CMMotionManager` to detect the orientation, which still works in that case. 

P. S. Solution was inspired by one of the answers in this thread: http://stackoverflow.com/questions/4574693/ios-device-orientation-disregarding-orientation-lock

**Comment by nkezhaya** [comment]
+1

**Comment by nkezhaya** [comment]
@mamouneyya This actually didn't work for me. The `UIImage.imageOrientation` value seems to always `== .right`. Is this working reliably for you?

**Comment by mamouneyya** [comment]
@whitepaperclip Yes, it perfectly does. Please take a look at the mentioned PR.
