### ISSUE TITLE
Select Image or Take Photo and go to new ViewController

### ISSUE THREAD

**Issue by KorkyraBoyCRO** [ytakzk/Fusuma#122]
Hi,

Is it possible to make minor modifications with code so after selecting photo or taking it it takes me to new view controller for example uploadViewcontroller where is selected image presented ( later it would be good to make another view after taking photo to confirm it or retake)?

**Comment by v-ken** [comment]
I made a pull request to manually dismiss Fusuma
https://github.com/ytakzk/Fusuma/pull/149

With this, you could choose to present Fusuma in a NavController and push your new ViewController onto the stack when you receive the corresponding Fusuma delegate callbacks.

**Comment by dkswe21** [comment]
I am also struggling to send selected images or captured image to new controller and I am totally new in swift so please help me to solve my problem.
