### ISSUE TITLE
Any plan to support a custom rectangular ratio?

### ISSUE THREAD

**Issue by sebayaki** [ytakzk/Fusuma#124]
I was planning to implement custom ratio settings myself, but it was harder than I thought.
Have anyone done similar forks?

Or I would appreciate if someone can make a suggestion on the best way to implement something like: 

```
fusuma.cropRatio = [4, 3] // 4:3 ratio
```

**Comment by sebayaki** [comment]
I ended up implemented the feature myself.

Here's the commit:
https://github.com/sydneyitguy/Fusuma/commit/27f7916a332f8b558addf411b0518d3682eb1270

Please let me know if you want to merge this feature, I'll create a PR

**Comment by ytakzk** [comment]
@sydneyitguy I will merge the implementation if you give me the PR.

**Comment by ytakzk** [comment]
@sydneyitguy i merged your PR. Thanks!
