### ISSUE TITLE
Mode switch not working

### ISSUE THREAD

**Issue by sstepanovvl** [ytakzk/Fusuma#125]
First of all  thank you for your awesome work !
several days ago i made a decision to use you library in my project, but unfortunately i stucked with a problem. Fusuma not doing mode switch :)
all i want is to show camera view instead of  library when view appears

i’ve tried both params with no luck

```
 @IBAction func showButtonPressed(_ sender: AnyObject) {
        // Show Fusuma
        let fusuma = FusumaViewController()
        
        fusuma.mode = .camera
                
        //        fusumaCropImage = false
        
        fusuma.delegate = self
        self.present(fusuma, animated: true, completion: nil)
    }
```

and:
        
 ```
@IBAction func showButtonPressed(_ sender: AnyObject) {
        // Show Fusuma
        let fusuma = FusumaViewController()
                
        fusuma.modeOrder = .cameraFirst
        
        //        fusumaCropImage = false
        
        fusuma.delegate = self
        self.present(fusuma, animated: true, completion: nil)
    }

```

Maybe i’m doing smthng wrong? is there any way i can fix it ?

Here is video with experiments:
[https://youtu.be/VpocO3dCw5I](https://youtu.be/VpocO3dCw5I)

@sydneyitguy any ideas, mate?

**Comment by jakubknejzlik** [comment]
If I'm not mistaken, It's due to `FusumaViewController` has the `enum Mode` and `var mode` not marked as public.

**Comment by ytakzk** [comment]
@sstepanovvl It works now 👍
