### ISSUE TITLE
Extension of FusumaDelegate implementing optional functions needs to be public

### ISSUE THREAD

**Issue by andreyrd** [ytakzk/Fusuma#131]
`fusumaDismissedWithImage` and `fusumaClosed` should be optional but as of commit 557c607dc6cf940edfdb17c690406618e23ff04f that is no longer working correctly.

The extension that implements the two optional methods has `internal` access level, so it's not seen outside of the library source. It needs to be made `public`.

```
public protocol FusumaDelegate: class {
    // MARK: Required
    func fusumaImageSelected(_ image: UIImage, source: FusumaMode)
    func fusumaVideoCompleted(withFileURL fileURL: URL)
    func fusumaCameraRollUnauthorized()
 
    // MARK: Optional
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode)
    func fusumaClosed()
}

extension FusumaDelegate {
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode) {}
    func fusumaClosed() {}
}
```

needs to become

```
public protocol FusumaDelegate: class {
    // MARK: Required
    func fusumaImageSelected(_ image: UIImage, source: FusumaMode)
    func fusumaVideoCompleted(withFileURL fileURL: URL)
    func fusumaCameraRollUnauthorized()
 
    // MARK: Optional
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode)
    func fusumaClosed()
}

public extension FusumaDelegate {
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode) {}
    func fusumaClosed() {}
}
```

**Comment by MinsungHuh** [comment]
I also agree!

**Comment by mhtranbn** [comment]
Did you think it work ?  @MinsungHung
`public protocol FusumaDelegate: class {
    // MARK: Required
    func fusumaImageSelected(_ image: UIImage, source: FusumaMode)
    func fusumaVideoCompleted(withFileURL fileURL: URL)
    func fusumaCameraRollUnauthorized()
 
    // MARK: Optional
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode)
    func fusumaClosed()
}

public extension FusumaDelegate {
    func fusumaDismissedWithImage(_ image: UIImage, source: FusumaMode) {}
    func fusumaClosed() {}
}`
