### ISSUE TITLE
Carthage to use latest version

### ISSUE THREAD

**Issue by DerkBusser** [ytakzk/Fusuma#132]
Hi, i am trying to update fusuma through carthage to version 1.0.1, but only 0.6 is available. How come? And how can i install the latest version through carthage?

**Comment by bishalg** [comment]
I just did 
`carthage update Fusuma --platform iOS --no-use-binaries`
and its working fine - 
```
*** Checking out Fusuma at "1.0.1"
*** Building scheme "Fusuma" in Fusuma.xcworkspace
```

**Comment by ytakzk** [comment]
@bishalg Thank you for answering instead of me.
