### ISSUE TITLE
FusumaDelegate

### ISSUE THREAD

**Issue by asaxionis** [ytakzk/Fusuma#133]
It appears that when I try to implement this in my project, FusumaDelegate is an undeclared type; Yet this works in the example project on the github; i have properly installed the cocoapods but don't know why i am getting this issue; code is below, but all it is, is an exact copy of the VC for the example, just in a different class

http://paste.ee/p/hbp9w

**Comment by JPwharton** [comment]
Hey not sure if this is what your asking, but I found that importing Fusuma, then calling the delegate, and manually entering the functions worked.  Swift 3 xcode functions varied from the documentation.

**Comment by TheNotoriousCoder** [comment]
I thought you must import it?

**Comment by ytakzk** [comment]
@JPwharton Yes, as @TheNotoriousCoder mentioned above, you must import the framework first.
