### ISSUE TITLE
Crash when updating images in photoLibraryDidChange

### ISSUE THREAD

**Issue by aterite** [ytakzk/Fusuma#135]
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (730) must be equal to the number of items contained in that section before the update (730), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).

FSAlbumView.swift line 333
FSAlbumView.(photoLibraryDidChange(PHChange) -> ()).(closure #1)

**Comment by parth51** [comment]
I add below code for fix the crash. The crash is occurring on my app is due to delete any album picture and come back to my application. So in this scenario, I just reload the data.

```
if !collectionChanges!.hasIncrementalChanges || collectionChanges!.hasMoves || (collectionChanges!.removedIndexes != nil){
                    collectionView.reloadData()
                }
```

**Comment by ytakzk** [comment]
@aterite Fixed 👍
