### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by normida** [ytakzk/Fusuma#137]
Hi, so I tried to use Fusuma on my project by install it manually since installing via cocoa pod didn't work with me. I drop classes  folder and Fusuma.framework to my project. The problem is when I tried to run the project the simulator crush by this error. I build a blank view controller and I connect it with camera button from home view controller.

dyld: Library not loaded: @rpath/Fusuma.framework/Fusuma
  Referenced from: /Users/*********/Library/Developer/CoreSimulator/Devices/8C31D581-921C-41FF-8EA9-73ABA8408E5F/data/Containers/Bundle/Application/1EEE1C1C-AF80-49B1-AED2-5C314B9942ED/****.app/****

  Reason: image not found

so how can I avoid this problem? I thought maybe because I didn't include images to assets.xcassets.

Another thing I would like to know, there isn't a detailed for Fusuma manual installation. is there anyway to learn about it so I can avoid issues and errors?

Waiting for your help guys

**Comment by ytakzk** [comment]
@normida Do you still have the problem now?

**Comment by normida** [comment]
Yes, I still have this problem @ytakzk

**Comment by Jackc415** [comment]
I also have this problem :/
