### ISSUE TITLE
Feature: Allow to set default mode (camera/library)

### ISSUE THREAD

**Issue by tschoffelen** [ytakzk/Fusuma#15]

**Comment by ytakzk** [comment]
@tschoffelen Let me add the feature in a few days. Thanks!

**Comment by ytakzk** [comment]
@tschoffelen I am happy to announce that you can select the default mode by

```
fusuma.defaultMode = FusumaMode.Camera // The default value is FusumaMode.Library
```

**Comment by lexrus** [comment]
@ytakzk This var is not public so that I can't access to it while Fusuma was installed with CocoaPods in my project.

**Comment by ytakzk** [comment]
Let me fix when I am back.

**Comment by codenameDuchess** [comment]
Thanks for this awesome Library! :-) Unfortunately, I am not able to access this defaultMode property either (CocoaPods install).   Is this enhancement for cocoapods still in development?  

I am setting fusuma.modeOrder = FusumaModeOrder.CameraFirst but it's still starting in library mode.

**Comment by yannbu** [comment]
@codenameDuchess Same problem here, did you figure it out ?
