### ISSUE TITLE
Use Fusuma with Objective-C 

### ISSUE THREAD

**Issue by dsouzarc** [ytakzk/Fusuma#150]
I saw a couple of issues with using Fusuma in an Objective-C project [here](https://github.com/ytakzk/Fusuma/issues/142) and [here](https://github.com/ytakzk/Fusuma/issues/58) but they were closed.

Does anyone know how to use Fusuma with Objective-C? Or would they mind writing some instructions?

**Comment by j005u** [comment]
pod gave me 1.0.3 by default, the issue seems to be fixed in 1.0.4.

I just changed the line in my Podfile to
`pod 'Fusuma', :git => 'https://github.com/ytakzk/Fusuma.git'`
Now everything is properly exposed to obj-c.

**Comment by ytakzk** [comment]
@dsouzarc As @j005u said, it is already fixed 👍
