### ISSUE TITLE
 Integrating Fusuma in my objective-c

### ISSUE THREAD

**Issue by anitalanet** [ytakzk/Fusuma#155]
Hi there

I am integrating Fusuma in my objective-c app

Now i am able to acess FusumaViewController but not able to acess the FusumaDelegate

I have seen my projectName-Swift.h file i can see the FusumaViewController's function but can not able to see the delegate function in it

Can someone please help me to resolve the issue

Thanks in advance

**Comment by chirag225** [comment]
same question Here How to use this lib in Objective c

**Comment by anitalanet** [comment]
I got the solution

**Comment by danieleferemo** [comment]
@anitalanet please what is the solution?

**Comment by ytakzk** [comment]
@danieleferemo Is that still failed?

**Comment by danieleferemo** [comment]
Hi @ytakzk still failed. Trying to implement it so i can choose multiple photos at once and pass to another view Controller in objective C, but can not access the FusumaDelegate.

**Comment by jeffreyjackson** [comment]
im having the same issue as @danieleferemo

**Comment by ytakzk** [comment]
#184
