### ISSUE TITLE
pod install only get version 1.0.3

### ISSUE THREAD

**Issue by hfzwhd** [ytakzk/Fusuma#159]
pod cache clear, pod repo update, pod update but still dont get the latest. also pod outdated command still dont show Fusuma. 

ps - trying to get 1.0.4

**Comment by hfzwhd** [comment]
this will do 
pod 'Fusuma',:git => "https://github.com/ytakzk/Fusuma.git", :branch => 'master'

**Comment by bishalg** [comment]
is something is wrong with the version number ? 
im using Carthage and it gets 1.0.4 which can't be compiled and had to change to 1.0.3 which works.

**Comment by ytakzk** [comment]
@hfzwhd Can you try again? You will install 1.1.0 👌
