### ISSUE TITLE
Return a PHAsset URL

### ISSUE THREAD

**Issue by gluecode** [ytakzk/Fusuma#16]
It would be nice to get the PHAsset URL so that image info like location can be extracted.

**Comment by ytakzk** [comment]
@gluecode Yes, it is useful for some cases. I will add the delegate method which returns the PHAsset URL

**Comment by LoganHenderson** [comment]
Would also love to see this delegate method added. Need to pull location data as well.

**Comment by Rashesh-Bosamiya** [comment]
let me know if you have added this feature.

I want URL for image as well.

**Comment by ytakzk** [comment]
@gluecode We now pass the ImageMetadata via fusumaImageSelected.
