### ISSUE TITLE
Delegates methods are never getting called

### ISSUE THREAD

**Issue by billionbucks** [ytakzk/Fusuma#160]
i'm using this this library via cocoaPods and when i'm selecting any image it's not triggering the delegate method. i made sure of i'm setting delegate of it on my ViewController, and only one of the delegate method is getting called which is `fusumaClosed()` also when i'm tapping the `doneButton` FusumaView gets disappear but nothing in return.

any idea why is this happening?

**Comment by peihsendoyle** [comment]
true, I'm in stuck with these delegates. `fusumaClosed()` and `fusumaWillClose()` never get called.

**Comment by sergioutama** [comment]
@billionbucks @peihsendoyle you can check #182
