### ISSUE TITLE
Carthage fails

### ISSUE THREAD

**Issue by douglas-srs** [ytakzk/Fusuma#161]
I'm trying to install using Carthage but it fails to build, when manually trying to build I get this error:

`.../Carthage/Checkouts/Fusuma/Sources/FusumaViewController.swift:39:10: Method cannot be a member of an @objc protocol because the type of the parameter 3 cannot be represented in Objective-C`

**Comment by douglas-srs** [comment]
Solved! Just used this in my cartfile instead:

`github "ytakzk/Fusuma" "master"`

**Comment by ytakzk** [comment]
@douglas-srs I will close this.
