### ISSUE TITLE
Little Space at the bottom(with screen shots)

### ISSUE THREAD

**Issue by Bomiishere** [ytakzk/Fusuma#163]
First of all, this is a great framework! Thanks a lot!

May I ask why there's a little small white space at the bottom that is not filled for the first time when I present the fusuma viewcontroller? 

The picture below: first picture is the first time enter in the viewcontroller, the second one is when I tapped back for the second time.

![fullsizeoutput_a73](https://cloud.githubusercontent.com/assets/17042189/25566983/97509e7e-2e16-11e7-8398-fbbc6985b276.jpeg)
![fullsizeoutput_a74](https://cloud.githubusercontent.com/assets/17042189/25566984/9792d532-2e16-11e7-94e5-0cc29eb5aea6.jpeg)

**Comment by jjjeeerrr111** [comment]
This shows you that you are on the camera roll tab. If you press the camera icon the "space" will transfer underneath the camera tab.

**Comment by Bomiishere** [comment]
Sorry I didn't explain well. This is what I mean

![seperate](https://cloud.githubusercontent.com/assets/17042189/25571024/80252840-2e5d-11e7-84cc-9e912d546d91.png)

**Comment by jenlai1345** [comment]
I'm experiencing the same issue...

**Comment by jenlai1345** [comment]
I added a very ugly hack at the very end of viewDidLoad() to make it for for now. I suspect it has to do with the button view hasn't been rendered fully at the time when the white bar is draw. 

        // hack (I made the camera instead of the camera roll as the default when it's opened )
        cameraButton.addBottomBorder(fusumaTintColor, width: 3)

**Comment by Bomiishere** [comment]
@jenlai1345 I've tried a better way.

You can add
```
highlightButton(libraryButton)
```
at the very bottom in viewDidLoad(), it will fix the issue.

**Comment by ytakzk** [comment]
@Bomiishere I think this is already fixed. Try update it to 1.1.0.
