### ISSUE TITLE
Pod installation project build error

### ISSUE THREAD

**Issue by ashfaqueahmed** [ytakzk/Fusuma#166]
![screen shot 2017-05-11 at 1 00 45 pm](https://cloud.githubusercontent.com/assets/2471993/25937762/879a4f98-364a-11e7-98f6-97ba1d6a7792.png)
I am using Xcode 7.3.1, after installation. Project build error.

**Comment by ytakzk** [comment]
@ashfaqueahmed Do you use Swift3? It seems to be Swift 2.x
