### ISSUE TITLE
With cocoapods(1.0.3) after capture directly image loads

### ISSUE THREAD

**Issue by UmaMadhavi** [ytakzk/Fusuma#169]
@ytakzk .. After capturing Image it is not possible to crop soon after capture image is loading .Please resolve the issue ?

**Comment by ytakzk** [comment]
@UmaMadhavi Can you please tell me more specific about that?

**Comment by UmaMadhavi** [comment]
@ytakzk Please let me know how can i modify this

**Comment by philip-ponder** [comment]
@ytakzk Was this resolved? We are also trying to get the preview page to show the image after its captured, and before dismissing FusumaViewController. When I take a photo, it immediately dismisses and returns the image in ImageSelected.

hasVideo = false
crop = true
colors changed, and delegate set, but that's all I've done.

I would also like to point out that it would be nice to toggle the statusBarHidden in the controller somehow.

Thanks
