### ISSUE TITLE
default mode photo launches with a static image

### ISSUE THREAD

**Issue by redwards72git** [ytakzk/Fusuma#170]
Xcode 8.3.2
Target 10.3

When presenting with photo as default, the window is static and doesn't display moving feed.
If library or Movie selected and then reselect photo, moving feed is restored

**Comment by ytakzk** [comment]
@redwards72git I updated Fusuma to 1.1.0. Could you try again after reinstalling?

**Comment by redwards72git** [comment]
Thanks fixed.
