### ISSUE TITLE
Images not rendering in collection view of FSAlbumView in iPad Air and iPad Air 2.

### ISSUE THREAD

**Issue by leapfrog-saugat** [ytakzk/Fusuma#18]
The images in the collectionView of the FSAlbumView are not being rendered in iPad Air and iPad Air 2. The frames are there. Also if I give the background color to the imageView the the background colors are visible. Even when I select the cell, the corresponding image is shown in the imageCropView. But the images are not being rendered in the collection view.

![blackclosed1](https://cloud.githubusercontent.com/assets/11421746/14071665/0b59883c-f4d7-11e5-8066-244e8e1db78c.png)
![redclosed1](https://cloud.githubusercontent.com/assets/11421746/14071664/0a19937c-f4d7-11e5-9cbb-cf19fe22e1d9.png)
![blackopen1](https://cloud.githubusercontent.com/assets/11421746/14071667/0b5de6b6-f4d7-11e5-8758-8b8981d9303f.png)
![redopen1](https://cloud.githubusercontent.com/assets/11421746/14071666/0b5d4e54-f4d7-11e5-96ff-09a23175ff22.png)

**Comment by leapfrog-saugat** [comment]
I forgot to mention that this problem occurs if the target of the app is iPhone instead of universal. Great library by the way. Your work has been very helpful to me. Thanks.

**Comment by ytakzk** [comment]
@leapfrog-saugat Does it also happen when you use the actual devices, not the simulators?

**Comment by saugat135** [comment]
@ytakzk Sorry for the late reply. Yes it does happen on the actual devices. But I found the source of the problem. In the FSCameraView flash was used without checking if the device actually supported flash. I checked the hasFlash property of device and handled the case accordingly.

**Comment by saugat135** [comment]
Hi @ytakzk  Sorry for the late reply. I tested on iPad 2 and iPad 4 and did not encounter any problem. But then they were working fine on their simulator counterparts as well. The main issue was in iPad Air and iPad Air 2. I was not able to test on the actual devices. So for now I am closing this issue.

**Comment by saugat135** [comment]
But I do have another genuine issue where the app crashes in iPad 2, if attempting to use flash while taking picture. I have found its solution as well. I am opening that issue.

**Comment by ytakzk** [comment]
@leapfrog-saugat If possible, could you send me the pull requests for those bug fixes?

**Comment by leapfrog-saugat** [comment]
okay..

**Comment by ytakzk** [comment]
@saugat135 You sent me two pull requests. does either one fix this issue?

**Comment by leapfrog-saugat** [comment]
@ytakzk  No. I have yet to check on the iPad Air. I don't have the device right now. You can close the issue if you like.

**Comment by ytakzk** [comment]
@leapfrog-saugat Ok, I can reproduce this issue but I have no idea to fix this problem.

**Comment by leapfrog-saugat** [comment]
Does the issue still persist if the app target is set to universal?

**Comment by leapfrog-saugat** [comment]
@ytakzk  I will also look into the issue throughout the next week. I hope we will find the solution.

**Comment by ytakzk** [comment]
@leapfrog-saugat No, it just happens when the target of the app is iPhone. I also hope we will find the solution. If you find the solution, please send me the pull request.

**Comment by leapfrog-saugat** [comment]
sure..
