### ISSUE TITLE
No delegate in Objective-C Project?

### ISSUE THREAD

**Issue by windshadowlam** [ytakzk/Fusuma#184]
![image](https://user-images.githubusercontent.com/8063971/27821545-3c58ec78-60d5-11e7-91a6-97f0f00f4190.png)
Cannot find and set the delegate in the VC

**Comment by ytakzk** [comment]
@windshadowlam Unfortunately, you can't since it includes struct so you cannot call the delegate from objc. I you want to use Fusuma from objc, you have to write a wrapper class which controls Fusuma.
