### ISSUE TITLE
viewDidLoad() for the base View controller is called twice when dismiss button pressed

### ISSUE THREAD

**Issue by ahmadmssm** [ytakzk/Fusuma#185]
When i present the Fusuma view controller then press dismiss button without selecting and image the call back function fusumaDismissedWithImage () in the base view controller is called then viewWillAppear() the viewDidLoad() called again then viewWillAppear() is called again too.

**Comment by ytakzk** [comment]
@ahmedmssm I cannot reproduce it. Can you see my sample code?
