### ISSUE TITLE
How to preset under status bar?

### ISSUE THREAD

**Issue by Faydee1220** [ytakzk/Fusuma#191]
How to preset under status bar?

I change the Library View and Menu View's top constraint to 20 in FusumaViewController.xib, but there must be a better way without change the pod file, right?

**Comment by ytakzk** [comment]
@Faydee1220 It is not possible now without installing source codes.

**Comment by SalvatoreAD** [comment]
I solved by adding a 20px height top view in the FusumaViewController.xib file
