### ISSUE TITLE
How disable zoom out 

### ISSUE THREAD

**Issue by francodriansetti** [ytakzk/Fusuma#196]
How to disable zoom out? 

I've tried the example app, and when I zoomed out I got a wrong cropped image. 

![fullsizerender](https://user-images.githubusercontent.com/7194678/28829897-904587ea-76d5-11e7-8bbc-23c9c15a7d6f.jpg)
![img_1897](https://user-images.githubusercontent.com/7194678/28829898-90700c68-76d5-11e7-8cee-4600944c3400.PNG)

**Comment by ytakzk** [comment]
@francodriansetti Is that the latest version of Fusuma?
I have tried but I got the correct cropped image.

![simulator screen shot 2017 08 02 11 21 47](https://user-images.githubusercontent.com/7313406/28854981-f70c7232-7774-11e7-8eda-e1995e00b0ff.png)

![simulator screen shot 2017 08 02 11 21 50](https://user-images.githubusercontent.com/7313406/28854984-03d68552-7775-11e7-88c9-a1ed556ded55.png)

**Comment by francodriansetti** [comment]
@ytakzk I use the latest version.
In your case works properly because you don't do zoom out.
If you see my photo (in the first image) there're is space on the top and on the bottom.

Can you please test with zoom out?

**Comment by vsandeepraju-pcs** [comment]
@francodriansetti, I do face the same issue... could someone help in this?

**Comment by francodriansetti** [comment]
@vsandeepraju-pcs did u found a solution?

**Comment by purplecofe** [comment]
I have same problem

**Comment by shenditya** [comment]
@francodriansetti  i have same problem too, then i just set minimum scale to 1.

FSImageCropView.swift
...
self.minimumZoomScale = 1 
...
