### ISSUE TITLE
how to get image file path I select?

### ISSUE THREAD

**Issue by XOneto9** [ytakzk/Fusuma#197]
Hi,

I'm David.
I faced some problem, I need to find photo path in local's iPhone photo library Image.

When I select the photo through Fusuma UI, Then I get a photo path...

how can I get that???

**Comment by ytakzk** [comment]
@XOneto9 I'm sorry but you can't get the path. I will consider to provide a PHAsset object for the selected image.

**Comment by ytakzk** [comment]
@XOneto9 The delegate method passes the PHAsset object so you can get the url.

**Comment by singh-karan-7** [comment]
How to retrieve image url using this asset? It doesn't seem to be working if we use PHAsset.
