### ISSUE TITLE
 Is it possible to increase navigation bar height of fusuma view controller ?

### ISSUE THREAD

**Issue by marioffmarques** [ytakzk/Fusuma#206]

**Comment by ytakzk** [comment]
@marioffmarques No you cannot do that now.

**Comment by ahmedsafadii** [comment]
you can from here

<img width="1919" alt="screen shot 2018-01-09 at 12 42 29 pm" src="https://user-images.githubusercontent.com/6974081/34717111-97fa3538-f53a-11e7-848f-4b61dc2b57f6.png">
