### ISSUE TITLE
how to ensure images taken in any angle will alway be upright in crop / square mode?

### ISSUE THREAD

**Issue by kohdesmond** [ytakzk/Fusuma#208]
Hi my issues as above.

Cheers

**Comment by jnkfong** [comment]
` func squareCropVideo(inputURL: NSURL, completion: @escaping (_ outputURL : NSURL?) -> ())
    {
        let videoAsset: AVAsset = AVAsset( url: inputURL as URL )
        let clipVideoTrack = videoAsset.tracks( withMediaType: AVMediaType.video ).first! as AVAssetTrack
        
        let composition = AVMutableComposition()
        composition.addMutableTrack(withMediaType: AVMediaType.video, preferredTrackID: CMPersistentTrackID())
        
        let videoComposition = AVMutableVideoComposition()
        videoComposition.renderSize = CGSize( width: clipVideoTrack.naturalSize.height, height: clipVideoTrack.naturalSize.height )
        videoComposition.frameDuration = CMTimeMake(1, 30)
        
        let transformer = AVMutableVideoCompositionLayerInstruction(assetTrack: clipVideoTrack)
        
        let instruction = AVMutableVideoCompositionInstruction()
        instruction.timeRange = CMTimeRangeMake(kCMTimeZero, CMTimeMakeWithSeconds(60, 30))
        
        transformer.setTransform(self.configureTransformation(clipVideoTrack: clipVideoTrack), at: kCMTimeZero)
        
        instruction.layerInstructions = [transformer]
        videoComposition.instructions = [instruction]
        
        let exportSession = AVAssetExportSession(asset: videoAsset, presetName: AVAssetExportPresetHighestQuality)!
        print ("random id = \(NSUUID().uuidString)")
        
        let croppedOutputFileUrl = URL( fileURLWithPath: NSTemporaryDirectory() + NSUUID().uuidString + ".mov")
        exportSession.outputURL = croppedOutputFileUrl
        exportSession.outputFileType = AVFileType.mov
        exportSession.videoComposition = videoComposition
        
        exportSession.exportAsynchronously(completionHandler: {
            if exportSession.status == .completed {
                print("Export complete")
                DispatchQueue.main.async(execute: {
                    completion(croppedOutputFileUrl as NSURL)
                })
                return
            } else if exportSession.status == .failed {
                print("Export failed - \(String(describing: exportSession.error))")
            }
            
            completion(nil)
            return
        })
    }
    
    func configureTransformation(clipVideoTrack:AVAssetTrack) -> CGAffineTransform {
        
        if(clipVideoTrack.naturalSize.width == clipVideoTrack.naturalSize.height){
            //already a square
            return clipVideoTrack.preferredTransform
        }
        
        let videoTransform:CGAffineTransform = clipVideoTrack.preferredTransform
        let orientation:UIInterfaceOrientation = self.getVideoOrientation(transform: videoTransform, track: clipVideoTrack)
        let transform1: CGAffineTransform
        var transform2: CGAffineTransform
        switch(orientation){
        case .portrait:
            transform1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)
            transform2 = transform1.rotated(by: .pi/2)
            break
        case .portraitUpsideDown:
            transform1 = CGAffineTransform(translationX: 0, y:clipVideoTrack.naturalSize.width - ((clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2))
            transform2 = transform1.rotated(by: -.pi/2)
            break
        case .landscapeLeft:
            transform1 = CGAffineTransform(translationX:clipVideoTrack.naturalSize.width - ((clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2), y: clipVideoTrack.naturalSize.height)
            transform2 = transform1.rotated(by: .pi)
            break
        case .landscapeRight:
            transform1 = CGAffineTransform(translationX:0 - ((clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2),y: 0);
            transform2 =  transform1.rotated(by: 0)
            break
        default:
            transform1 = videoTransform
            transform2 = transform1.rotated(by: 0)
            break
        }
        
        return transform2
    }
    
    func getVideoOrientation(transform:CGAffineTransform, track: AVAssetTrack) -> UIInterfaceOrientation {
        switch (transform.tx, transform.ty) {
        case (0, 0):
            return .landscapeRight
        case (track.naturalSize.width, track.naturalSize.height):
            return .landscapeLeft
        case (0, track.naturalSize.width):
            return .portraitUpsideDown
        default:
            return .portrait
        }
        
    }`

**Comment by jnkfong** [comment]
` func squareCropVideo(inputURL: NSURL, completion: @escaping (_ outputURL : NSURL?) -> ())
    {
        let videoAsset: AVAsset = AVAsset( url: inputURL as URL )
        let clipVideoTrack = videoAsset.tracks( withMediaType: AVMediaType.video ).first! as AVAssetTrack
        
        let composition = AVMutableComposition()
        composition.addMutableTrack(withMediaType: AVMediaType.video, preferredTrackID: CMPersistentTrackID())
        
        let videoComposition = AVMutableVideoComposition()
        videoComposition.renderSize = CGSize( width: clipVideoTrack.naturalSize.height, height: clipVideoTrack.naturalSize.height )
        videoComposition.frameDuration = CMTimeMake(1, 30)
        
        let transformer = AVMutableVideoCompositionLayerInstruction(assetTrack: clipVideoTrack)
        
        let instruction = AVMutableVideoCompositionInstruction()
        instruction.timeRange = CMTimeRangeMake(kCMTimeZero, CMTimeMakeWithSeconds(60, 30))
        
        transformer.setTransform(self.configureTransformation(clipVideoTrack: clipVideoTrack), at: kCMTimeZero)
        
        instruction.layerInstructions = [transformer]
        videoComposition.instructions = [instruction]
        
        let exportSession = AVAssetExportSession(asset: videoAsset, presetName: AVAssetExportPresetHighestQuality)!
        print ("random id = \(NSUUID().uuidString)")
        
        let croppedOutputFileUrl = URL( fileURLWithPath: NSTemporaryDirectory() + NSUUID().uuidString + ".mov")
        exportSession.outputURL = croppedOutputFileUrl
        exportSession.outputFileType = AVFileType.mov
        exportSession.videoComposition = videoComposition
        
        exportSession.exportAsynchronously(completionHandler: {
            if exportSession.status == .completed {
                print("Export complete")
                DispatchQueue.main.async(execute: {
                    completion(croppedOutputFileUrl as NSURL)
                })
                return
            } else if exportSession.status == .failed {
                print("Export failed - \(String(describing: exportSession.error))")
            }
            
            completion(nil)
            return
        })
    }
    
    func configureTransformation(clipVideoTrack:AVAssetTrack) -> CGAffineTransform {
        
        if(clipVideoTrack.naturalSize.width == clipVideoTrack.naturalSize.height){
            //already a square
            return clipVideoTrack.preferredTransform
        }
        
        let videoTransform:CGAffineTransform = clipVideoTrack.preferredTransform
        let orientation:UIInterfaceOrientation = self.getVideoOrientation(transform: videoTransform, track: clipVideoTrack)
        let transform1: CGAffineTransform
        var transform2: CGAffineTransform
        switch(orientation){
        case .portrait:
            transform1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)
            transform2 = transform1.rotated(by: .pi/2)
            break
        case .portraitUpsideDown:
            transform1 = CGAffineTransform(translationX: 0, y:clipVideoTrack.naturalSize.width - ((clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2))
            transform2 = transform1.rotated(by: -.pi/2)
            break
        case .landscapeLeft:
            transform1 = CGAffineTransform(translationX:clipVideoTrack.naturalSize.width - ((clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2), y: clipVideoTrack.naturalSize.height)
            transform2 = transform1.rotated(by: .pi)
            break
        case .landscapeRight:
            transform1 = CGAffineTransform(translationX:0 - ((clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2),y: 0);
            transform2 =  transform1.rotated(by: 0)
            break
        default:
            transform1 = videoTransform
            transform2 = transform1.rotated(by: 0)
            break
        }
        
        return transform2
    }
    
    func getVideoOrientation(transform:CGAffineTransform, track: AVAssetTrack) -> UIInterfaceOrientation {
        switch (transform.tx, transform.ty) {
        case (0, 0):
            return .landscapeRight
        case (track.naturalSize.width, track.naturalSize.height):
            return .landscapeLeft
        case (0, track.naturalSize.width):
            return .portraitUpsideDown
        default:
            return .portrait
        }
        
    }`
I used the following
