### ISSUE TITLE
How to enable not only square image, but if we zoom out to fit screen image, it should be like rectangle?

### ISSUE THREAD

**Issue by KanybekMomukeyev** [ytakzk/Fusuma#209]
How to enable not only square image, but if we zoom out to fit screen image, 
image should be like rectangle like on screen?

**Comment by vsandeepraju-pcs** [comment]
Am also looking for same... either it should not allow to zoom out the square area or it needs to return the image set in the crop view.

**Comment by purplecofe** [comment]
me too

**Comment by leo1mml** [comment]
me too
