### ISSUE TITLE
Add option not to select first image in photo library

### ISSUE THREAD

**Issue by neokoenig** [ytakzk/Fusuma#216]
By default, when you load the photo library view, the first image is always selected: it's not always 100% obvious to the user that that is the default behaviour.

How feasible is it to add a flag that means no images are selected by default?

**Comment by andrezacds** [comment]
I'd love that feature as well.

**Comment by jacobokoenig** [comment]
+1

**Comment by devender54321** [comment]
first time when you install your app . no image is selected by default
