### ISSUE TITLE
Flash doesn't trigger for rear camera

### ISSUE THREAD

**Issue by Bhide** [ytakzk/Fusuma#224]
Might be due to depreciation of AVCaptureStillImageOutput since iOS 10 and AVCaptureDevice's flashMode property won't take effect. Needs to be fixed.

https://developer.apple.com/documentation/avfoundation/avcapturephotosettings/1648760-flashmode

**Comment by carmelogallo** [comment]
Same problem here.

**Comment by nkezhaya** [comment]
This appears to be fixed.
