### ISSUE TITLE
pod install only get version 1.2.0 instead of 1.2.1

### ISSUE THREAD

**Issue by kohdesmond** [ytakzk/Fusuma#231]
HI @ytakzk as per my subject.

Can you kindly push the updated version to pods please?

Cheers!

**Comment by francodriansetti** [comment]
Use this: 
_pod 'Fusuma', :git => 'https://github.com/ytakzk/Fusuma.git', :branch => 'master'_

**Comment by ytakzk** [comment]
@kohdesmond I just have my mac repaired today. I will update soon!

**Comment by ytakzk** [comment]
updated 🎉
