### ISSUE TITLE
Add support to iPhone X

### ISSUE THREAD

**Issue by LimChihi** [ytakzk/Fusuma#233]
Hello, Thanks for your open sources.
I have found that Fusuma has not support to iPhone X.
I use swift 4 branch.
<img width="549" alt="2017-11-22 12 53 25" src="https://user-images.githubusercontent.com/18307084/33110696-ab82b8fe-cf84-11e7-9e2c-6f6498399532.png">

**Comment by LimChihi** [comment]
Is work perfect on iPhone X when i change branch to master.
Is it possible that update `swift4` branch to add this feature?

**Comment by ytakzk** [comment]
@LimChihi Fusuma is not fully compatible with Swift4 yet. 😢 
Please give me the PR, if possible.
