### ISSUE TITLE
iOS 11 Unable to load image

### ISSUE THREAD

**Issue by lukasbowen** [ytakzk/Fusuma#234]
I am currently, using the swift 4 branch. It appears in the newest version of iOS apple managed to to break the previous workflow apparently for loading images. The Camera Roll no longer loads and any files taken cannot be loaded. 
Is there any possibility of getting this fixed? 

Thanks.

**Comment by matthewfx** [comment]
Same here. Just have installed a cocoapod and tried to use it but a photo library is empty...

**Comment by nkezhaya** [comment]
The `swift4` branch has been deleted. Use `master` until I can update the pod repo.
