### ISSUE TITLE
Issue  after  update from cocoa pod from 1.2.0 to 1.2.3

### ISSUE THREAD

**Issue by UmaMadhavi** [ytakzk/Fusuma#235]

**Comment by ytakzk** [comment]
@UmaMadhavi Could you explain it in detail?

**Comment by UmaMadhavi** [comment]
@ytakzk . After update i got errors in 3 files which were not converted to swift 4

**Comment by salmank888** [comment]
I had same kind of issues.
I had Fusuma (1.2.4)

![screen shot 2018-04-10 at 7 31 07 pm](https://user-images.githubusercontent.com/10423669/38563257-d3b7b3cc-3cf5-11e8-824e-e93b253f97b7.png)

**Comment by salmank888** [comment]
I had Fusuma (1.2.4)
