### ISSUE TITLE
take some time(3-4seconds) after selecting photo

### ISSUE THREAD

**Issue by ryamashita** [ytakzk/Fusuma#236]
I am testing on iOS11, iphone5s, 6. It takes 3-4 seconds to dismiss the fusuma controller, after selecting photo(tapping on the top-right corner button). Is it possible to run faster?

**Comment by andrezacds** [comment]
Hi ryamashita.
Just out of curiosity, is your project on Swift 4? I just installed Fusuma, and it doesn't even compile...

**Comment by ryamashita** [comment]
Hi, Andreza.

I had same issue.
In my case,
- Swift 3.2
- pod "BSImagePicker", "2.5"
worked perfectly.

Not "2.4" or "2.7".



2017-12-06 9:11 GMT+09:00 Andreza <notifications@github.com>:

**Comment by andrezacds** [comment]
Unfortunately is not an option for me.... I need to be able to crop the pictures and select videos... Thank you, though
