### ISSUE TITLE
It does not compile on Swift 4

### ISSUE THREAD

**Issue by andrezacds** [ytakzk/Fusuma#237]
I just installed Fusuma with cocoaPods, but it doesn't compile on Swift 4. I get a total of 39 errors, among types that were renamed, some variable that was not unwrapped, obsolete functions and a few others.

**Comment by Faydee1220** [comment]
Edit your podfile as below, the "pod install" again
pod 'Fusuma', :git => 'https://github.com/ytakzk/Fusuma.git', :branch => 'swift4'

**Comment by ytakzk** [comment]
@andrezacds it's merged into master branch.
