### ISSUE TITLE
Weird visibility when scrolling up from Library on iPhone X

### ISSUE THREAD

**Issue by mbalex99** [ytakzk/Fusuma#242]
![image](https://user-images.githubusercontent.com/2183729/34428845-8a1f6732-ec05-11e7-98bd-14cf2454c069.png)

In Library mode, if you scroll up you get something like above. I'm on an iPhone X on iOS 11.2.1

**Comment by jacobokoenig** [comment]
+1.. Any news?

**Comment by maymard** [comment]
Also, on the iPhone X, after scrolling up and selecting an image, as soon as I touch the image (for example, trying to zoom in) the image automatically scrolls all the way up as shown in the previous comment.

**Comment by Lailan** [comment]
+1...  Any news?

**Comment by philipprovoost** [comment]
+1... Any news?

**Comment by mrhaxic** [comment]
+1... Any news?

**Comment by nkezhaya** [comment]
Keeping this issue in #275

**Comment by dhara6894** [comment]
not resolved, I am also facing same issue
![IMG_0723](https://user-images.githubusercontent.com/25882656/62848851-e321cd80-bcfa-11e9-949e-90c3b9cfc22c.PNG)
