### ISSUE TITLE
It is not possible to zoom in camera mode

### ISSUE THREAD

**Issue by facconi** [ytakzk/Fusuma#244]
It is not possible to zoom in camera mode, only in library mode.
I have searched documentation and other tools, without finding how to fix this issue.
Thanks

**Comment by momomatteo** [comment]
I have the same problem. Is there a way to zoom in camera mode?
Thanks

**Comment by fcbit** [comment]
Hi! Same issue here! Is there a solution?
Thank you!

**Comment by nkezhaya** [comment]
@facconi @momomatteo @fcbit Working on this now.

**Comment by nkezhaya** [comment]
@facconi @momomatteo @fcbit Pushed to master.
