### ISSUE TITLE
Getting first image from a recorded video

### ISSUE THREAD

**Issue by sebastienboulogne** [ytakzk/Fusuma#246]
Hi Guys, i was wondering if the feature already exists in the framework...

Can you get the first image from a video when it's finished to record. I mean in the method, you only get the fileUrl of the video but needs an UIImage too. 

How and where to implement this method ? Thx

**Comment by devender54321** [comment]
yes I am facing the same problem

**Comment by devender54321** [comment]
func fusumaVideoCompleted(withFileURL fileURL: URL) {
        
        print("Called just after a video has been selected.")
        print("video completed and output to file: \(fileURL)")
       // let stringFromPath = fileURL.absoluteString
        do {
            
            let asset = AVURLAsset(url: fileURL , options: nil)
            let imgGenerator = AVAssetImageGenerator(asset: asset)
            imgGenerator.appliesPreferredTrackTransform = true
            let cgImage = try imgGenerator.copyCGImage(at: CMTimeMake(0, 1), actualTime: nil)
            let thumbnail = UIImage(cgImage: cgImage)
            self.sendImage.append(thumbnail)
            self.type="video"

            self.performSegue(withIdentifier: "segue_compose", sender: self)
            
        }
        catch let error {
            print("*** Error generating thumbnail: \(error.localizedDescription)")
            
        }
        
        //self.fileUrlLabel.text = "file output to: \(fileURL.absoluteString)"
    }
