### ISSUE TITLE
Swift language version issue

### ISSUE THREAD

**Issue by chandraf22** [ytakzk/Fusuma#247]
<img width="1372" alt="screen shot 2018-01-24 at 16 44 38" src="https://user-images.githubusercontent.com/12895140/35329461-f7e32a62-0125-11e8-85e6-de22ce501e28.png">

I have to set the swift language version flag to swift 3.2 to run from cocoapods. By default, it was set to swift 4.0. I am working on a new project and the first pod I installed was Fusuma.

**Comment by michaelhenry** [comment]
You can install the previous/older version that is compatible with swift3.

**Comment by ytakzk** [comment]
@chandraf22 Yes, as @michaelhenry suggested, you should install the previous version for swift3.
