### ISSUE TITLE
Video Unable to Capture Audio, Not asking Micro Phone Usage Permission

### ISSUE THREAD

**Issue by Azar475** [ytakzk/Fusuma#251]
Able to capture Video Successfully, but Video does not contain Audio, when we launch app for the first time it didn't ask for  Micro Phone Usage Permission too, even though i have added "Privacy - Microphone Usage Description" in info Plist. Thank you.

**Comment by nathankonrad1** [comment]
Hey @Azar475 Please refer to 
https://github.com/ytakzk/Fusuma/issues/106

This worked for me.

Anyway, seems no one is update this library, so it will be very hard to use in next versions of iOS :(
