### ISSUE TITLE
"ic_insert_photo" &  "ic_photo_camera"  Not Found in cocoapods

### ISSUE THREAD

**Issue by voyager163** [ytakzk/Fusuma#257]
Could not load the "ic_insert_photo" image referenced from a nib in the bundle with identifier "org.cocoapods.Fusuma"

Could not load the "ic_photo_camera" image referenced from a nib in the bundle with identifier "org.cocoapods.Fusuma"

**Comment by BatyrOvezdurdyyev** [comment]
I had that error. How can we rid of it?

**Comment by voyager163** [comment]
Nope, you cannot

**Comment by voyager163** [comment]
I edit his project inside my fork. You can use it if required.

**Comment by delta2424** [comment]
i am comment or remove this line to solve problem me.
           "fusuma.allowMultipleSelection = true"
