### ISSUE TITLE
Can we select limited number of images

### ISSUE THREAD

**Issue by sagarsolace123** [ytakzk/Fusuma#259]
Here I didn't get the limitation to select multiple images from gallery,

**Comment by devender54321** [comment]
Yes I also want to do same with library

**Comment by devender54321** [comment]
replace the below with existing function

   func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        
         let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "FSAlbumViewCell", for: indexPath) as! FSAlbumViewCell
        
        
        
        if selectedImages.count < 10 && selectedAssets.count < 10 {
            changeImage(images[(indexPath as NSIndexPath).row])
            
            imageCropView.changeScrollable(true)
            
            imageCropViewConstraintTop.constant = imageCropViewOriginalConstraintTop
            collectionViewConstraintHeight.constant = self.frame.height - imageCropViewOriginalConstraintTop - imageCropViewContainer.frame.height
            
            UIView.animate(withDuration: 0.2,
                           delay: 0.0,
                           options: UIViewAnimationOptions.curveEaseOut,
                           animations: {
                            
                            self.layoutIfNeeded()
            }, completion: nil)
            
           
            
            dragDirection = Direction.up
            


            collectionView.scrollToItem(at: indexPath, at: .top, animated: true)
        }
        else
        {
            //cell.viewShade.isHidden = true
            
            collectionView.deselectItem(at: indexPath, animated: false)
        }

**Comment by devender54321** [comment]
import UIKit
import Photos

final class FSAlbumViewCell: UICollectionViewCell {
    
    @IBOutlet weak var viewShade: UIView!
    @IBOutlet weak var imageView: UIImageView!
    
    @IBOutlet weak var lblCount: UILabel!
    
    var image: UIImage? {
        
        didSet {
            
            self.imageView.image = image
            
        }
    }
    
    override func awakeFromNib() {
        
        super.awakeFromNib()
        self.isSelected = false
    }
    
   override var isSelected : Bool {
    
       didSet {

           self.viewShade.isHidden = isSelected ? false : true
        
       }
    }
}

**Comment by devender54321** [comment]
Process :- in Fusuma library class  FSAlbumView you can set limit for maximum (10 in my case)

in FSAlbumCell class take a view on image view and set a label within the view and in cell class use code.    self.viewShade.isHidden = isSelected ? false : true 

Hope it will help you
Enjoy

**Comment by mehroozkhanpl** [comment]
viewModel.photos.append(contentsOf: images)
        if viewModel.photos.count > 6 {
            viewModel.photos = Array(viewModel.photos[0...5])
            self.presentAlert("", message: Texts.maxImageSelection)
        }
        collectionView.reloadData()
