### ISSUE TITLE
Support For Swift 4.2

### ISSUE THREAD

**Issue by ljbdelacruz** [ytakzk/Fusuma#277]
hi i would like to ask if the support for swift 4 or swift 4.2 is available thanks

**Comment by spaquet** [comment]
Swift 4 yes
Swift 4.2 not (at the time of writing), but you can change the swift version required by this pod and have your project in Swift 4.2 while this pod remains in Swift 4.0

**Comment by nkezhaya** [comment]
@ljbdelacruz 1.3.0 uses Swift 4.2
