### ISSUE TITLE
selected image is not clearly indicated

### ISSUE THREAD

**Issue by andthereitgoes** [ytakzk/Fusuma#287]
Currently, when I select an image; the selected image opacity changes. This is not good UX because it's very difficult to make out easily (visually) whether the image is selected or not. 

Better UX would be to show a simple tick mark against the selected image. 

Is there any customisation that can be done through configuration to achieve this?

**Comment by andthereitgoes** [comment]
@whitepaperclip I would appreciate if you can leave a comment of why you are closing the issue?

**Comment by nkezhaya** [comment]
@andthereitgoes The point of the library is to mimic the Instagram photo picker.
