### ISSUE TITLE
support switch albums

### ISSUE THREAD

**Issue by Ferrick90** [ytakzk/Fusuma#29]
Can add switch albums to select the photo? It will help end-user easier to search their photo.

**Comment by ytakzk** [comment]
@Ferrick90 I always want to have this feature but have no time yet. However, I wIll definitely implement this.

**Comment by JohnKuan** [comment]
@ytakzk I am working on a version for switching albums for my use case. I will make a pull request after reviewing my code.

**Comment by mitesh53** [comment]
Can add switch albums to select the photo? It will help end-user easier to search their photo. plz its urgent
