### ISSUE TITLE
Animation issue for select gallery photo cell

### ISSUE THREAD

**Issue by Ferrick90** [ytakzk/Fusuma#30]
In FSAlbumView, once CollectionView didSelectItemAtIndexPath is calling and the main layout will change after collectionView will scrollToItemAtIndexPath. It make user see like a bit lagging. (sudden Down and Up) Hope can improve transition in future.

**Comment by ytakzk** [comment]
@Ferrick90 How it should be? It is almost the same animation as the one in Instagram. Anyway, thanks always!

**Comment by ytakzk** [comment]
I will reopen this issue when I receive the reply and understand what you mean.

**Comment by Ferrick90** [comment]
This is what I mean. In collectionView didSelectItemAtIndexPath put UIView.animationDuration to 0.6 second then you able to see what I saying.

![double_transition](https://cloud.githubusercontent.com/assets/6068413/14592716/47d3fb16-0554-11e6-8d84-c237042e7543.gif)
