### ISSUE TITLE
Allow not cropped photos

### ISSUE THREAD

**Issue by bitomule** [ytakzk/Fusuma#32]
Is it possible to not crop images picked from Fusuma? I love this controller but I need original images.

**Comment by MartinQue** [comment]
@bitomule , i think the whole essence is to have it constrained within that size. Hence why the photo browser layout and the camera view are all constrained within such size. What i could agree with tho, is to have the Image fit in a UIImageView with the view mode set to Aspect Fill.

**Comment by LadyRanger1992** [comment]
this issue currently visible.
