### ISSUE TITLE
How to use with objective-c?

### ISSUE THREAD

**Issue by afiq90** [ytakzk/Fusuma#34]
Hey there, how can I use this awesome libraries with objective-c?

**Comment by khoren93** [comment]
+1

**Comment by muhasturk** [comment]
Why do insistence that not use Swift in your project? Swift is future.

**Comment by ytakzk** [comment]
Now you can use Fusuma from objective-c project.

**Comment by sv9988** [comment]
Can you help me how to use this libraries in ObjC Project? Thanks you!

**Comment by ksatasiya** [comment]
give us your help for objective c for this library
