### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by glancashire** [ytakzk/Fusuma#35]
Hi

Thanks for the great work.

It would be great if your control was localized or localizable.

 titleLabel.text = "CAMERA ROLL"
 titleLabel.text = NSLocalizedString("CAMERA ROLL", comment: "CAMERA ROLL")

 titleLabel.text = "PHOTO"
 titleLabel.text = NSLocalizedString("PHOTO", comment: "PHOTO")

Kind Regards
Graham

**Comment by ytakzk** [comment]
#40
