### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by glancashire** [ytakzk/Fusuma#36]
Hi

Thanks for the great work.

It would be great if your control would support a light color scheme in addition to the existing dark scheme.

Kind Regards
Graham

**Comment by ytakzk** [comment]
It has already been implemented. We have these two variables. Then you can use your own colors.

```
fusumaTintColor: UIColor // tint color
fusumaBackgroundColor: UIColor // background color
```

**Comment by glancashire** [comment]
This does not work. Try using a white background ;-)

**Comment by ytakzk** [comment]
Oh, the color affects the header and the footer only.
Could you send me the pull request for that? This library is super simple so it will be easy for you to fix it.
I have no time right now..

**Comment by ytakzk** [comment]
#40
