### ISSUE TITLE
Save Taken Photo to Library 

### ISSUE THREAD

**Issue by muhasturk** [ytakzk/Fusuma#38]
How can I do this? Something like

``` swift
if let pickedImage = info[UIImagePickerControllerOriginalImage] as? UIImage {
      UIImageWriteToSavedPhotosAlbum(pickedImage, nil, nil, nil)
}
```

**Comment by ytakzk** [comment]
```
func fusumaImageSelected(image: UIImage) {

  print("Image selected")
}
```

You can get a selected image or a taken photo. You can save the photo to your camera roll inside this function.

**Comment by andreyrd** [comment]
There should be a built in feature that saves only photos taken with the _camera_. We don't have any way to tell if the image in fusumaImageSelected is from Photos or the camera, so if we always save it, we're going to end up with a lot of duplicates.
