### ISSUE TITLE
Video access and recording

### ISSUE THREAD

**Issue by rmuhamedgaliev** [ytakzk/Fusuma#4]
Can you add record croped video and select video from gallery?

**Comment by ytakzk** [comment]
@rmuhamedgaliev thank you for the request. I will implement the feature when I have time.

**Comment by waterskier2007** [comment]
If you are cool with it, I have started working on this and would love the chance to get it implemented.

**Comment by ytakzk** [comment]
@waterskier2007 That's super helpful with me. Waiting for your PR :+1:
