### ISSUE TITLE
Autolayout constraints in landscape not working properly

### ISSUE THREAD

**Issue by pixelskull** [ytakzk/Fusuma#50]
When device is rotated to landscape the view is not layed out properly. The following images demonstrate the problem on iPhone 5 (4" screen size). 

![img_1130](https://cloud.githubusercontent.com/assets/1270382/15978156/bc521b44-2f5c-11e6-8753-40c82431813d.jpg)
![img_1132](https://cloud.githubusercontent.com/assets/1270382/15978157/bc5aca00-2f5c-11e6-97b4-a2bedffa5a0a.jpg)
![img_1131](https://cloud.githubusercontent.com/assets/1270382/15978155/bc51ef5c-2f5c-11e6-9835-7630a1820e17.jpg)

**Comment by ytakzk** [comment]
@pixelskull Fusuma does not support landscape mode for now.

**Comment by luisgizirian** [comment]
Appreciate your call. Is it possible to get that behavior fixed at `FusumaViewController`? Then, for those building apps supporting a mixed set of layouts, it'd be really helpful to enforce the portrait only mode from the controller.

This code should be enough for raw testing.

```
override public func shouldAutorotate() -> Bool {
    return false
}

override public func supportedInterfaceOrientations() -> UIInterfaceOrientationMask {
    return UIInterfaceOrientationMask.Portrait
}
```

Would you prefer a pull-request? Thanks for the library!
