### ISSUE TITLE
Non-square videos and photos

### ISSUE THREAD

**Issue by Raymond26** [ytakzk/Fusuma#54]
Is there a setting to change the aspect ratio of the camera / picker?

**Comment by ytakzk** [comment]
@Raymond26
Do you mean the property of  `fusumaCropImage:Bool // default is true for cropping the image` ?

Unfortunately, Fusuma does not support the customized aspect ratio yet.

**Comment by MarvinNazari** [comment]
`fusumaCropImage:Bool` it works for the picture, but there is no way to crop to video that we record

**Comment by JackHM** [comment]
@ytakzk Hi I was wondering if there is a option to get different size images? for example if I zoom out on a image I can see some kind of aspect fit of it. IS there a way to crop it to that size? Just like the new instagram camera album does...Or do you know how I could achieve it? thanks in advance!

**Comment by ytakzk** [comment]
@Raymond26 @JackHM Done. 👍

**Comment by sasquatchgit** [comment]
How to achieve this?
