### ISSUE TITLE
Rotating photo after upload

### ISSUE THREAD

**Issue by byrustamzade** [ytakzk/Fusuma#56]
If i take photo from camera it rotates 90 degree after upload. Is there any solution?

**Comment by luisgizirian** [comment]
@byrustamzade , you may try passing the image thru this function (see Gist below). This is a device behaviour not specific to @ytakzk library.

https://gist.github.com/quangtqag/d2c64a2d3faf8f4550b6e20a47e561ef

**Comment by ytakzk** [comment]
@byrustamzade it has been fixed now.
