### ISSUE TITLE
Customizing Fusuma from objective-c project

### ISSUE THREAD

**Issue by khoren93** [ytakzk/Fusuma#58]
Hi, I used Fusuma in my project written in objective-c, all works correct, but i have not access to local variables like  fusumaTintColor or fusumaBackgroundColor. Can i customize Fusuma interface without changing source code in Fusuma lib?
Thanks:)

**Comment by NasirMalik** [comment]
I have same question. As I cannot see these properties declared inside FusumaViewController, but inside delegate so there seems little hope. When I command click on objectiveC FusumaViewController class it shows translated class without all of these variables. Let me know if there is any remedy.

**Comment by ililysong** [comment]
I have same question

**Comment by PattoMotto** [comment]
I use this in swift 3.0
```swift
let fusuma = FusumaViewController()
fusuma.delegate = self
fusumaTintColor = UIColor(red: 25/255.0,green: 211/255.0,blue: 203/255.0, alpha: 1)
self.present(fusuma, animated: true, completion: nil)
```
Hope it help you guys.

**Comment by ytakzk** [comment]
Fusuma depends on Struct so some properties cannot be used in Objective-C.
