### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Ferrick90** [ytakzk/Fusuma#63]
Do you plan to create a swift3 branch soon?

**Comment by andreyrd** [comment]
Here's an untested branch I just finished today:
https://github.com/andreyrd/Fusuma/tree/swift3

Let me know if it works, I don't have time to set up a new project to test it out, and my main project still has a lot more stuff I need to update to Swift 3 before I can run it. 😬

**Comment by ytakzk** [comment]
@Ferrick90 I finally updated the library to be compatible with swift3.

**Comment by devender54321** [comment]
How to fix limit fo maximum selection of images. And also how to numbered 1 2 3 and so on like Instagram
