### ISSUE TITLE
Map view

### ISSUE THREAD

**Issue by hymced** [ytakzk/Fusuma#65]
Hello

I am deeply looking for a tool that could display all my likes on a map (and not my own posts only as does ig right now)

Since your project seems to be the most active, I am putting this request here as an improvement. Maybe you could collaborate with this project to use Google Maps : https://github.com/haydenbleasel/photomap

Thank you for the attention you will give to my request ;)

Cheers

**Comment by ytakzk** [comment]
@hymced This must be another project so I won't include the future to Fusuma.
