### ISSUE TITLE
Video capture crash, reason flashMode

### ISSUE THREAD

**Issue by voidw0rd** [ytakzk/Fusuma#66]
App crash when activating video capture mode

Device: iPad Air 2

`FusumaExample[5376:2477109] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureVideoDevice setFlashMode:] - the passed flashMode 0 is not supported by the device.  Use -isFlashModeSupported: to discover valid flash modes.'`

clone the repository, add `fusuma.hasVideo = true` to ViewController.swift run the app

problem is FSVideoCameraView.swift, adding `guard device.hasFlash else { return }` before  `device.flashMode = AVCaptureFlashMode.Off` fixes the crash but the flashButton is still in the UI and users can press it, that will make the app crash with the same error, in Picture mode flashButton is not displayed

**Comment by ytakzk** [comment]
This has been fixed.
