### ISSUE TITLE
able to add fusumaDismissedWithoutImage Delegate?

### ISSUE THREAD

**Issue by Ferrick90** [ytakzk/Fusuma#7]
Hi,

I would to like to run fusumaDismissedWithoutImage delegate to do some coding inside.

Thanks.

Regards,
Ferrick Chan

**Comment by ytakzk** [comment]
@ Ferrick90 Do you mean that you would like to dismiss FusumaViewController programmatically?

**Comment by Ferrick90** [comment]
I have submitted the PR. Thanks

**Comment by ytakzk** [comment]
@Ferrick90 Let me close this issue now. When you think of the good use case of the delegate, please open this again.

**Comment by ytakzk** [comment]
I accepted the delegate method but renamed it. See 0.2.5. Thanks!
