### ISSUE TITLE
Torch mode in video instead of flash mode

### ISSUE THREAD

**Issue by itsmeichigo** [ytakzk/Fusuma#73]
Hi, I just found an issue with the torch mode of the camera when recording video. Currently in your code you're toggling `flashMode` of the device, which should be replaced with `torchMode` for the feature to work properly.

Anw, thanks for the library!

**Comment by Marini83** [comment]
Thank you it helps!

**Comment by nkezhaya** [comment]
@itsmeichigo Closing due to the age of the ticket. If you could open a PR it'd be appreciated.
