### ISSUE TITLE
FusumaViewController ignores modeOrder value

### ISSUE THREAD

**Issue by mamouneyya** [ytakzk/Fusuma#74]
It's hardcoded in the controller's viewDidLoad() to start with library mode, even if modeOrder's value is .CameraFirst.

**Comment by Cheesebaron** [comment]
I can confirm the enum isn't used at all.

**Comment by mamouneyya** [comment]
@ytakzk Any estimation for this?

**Comment by sstepanovvl** [comment]
any updates?

**Comment by ytakzk** [comment]
@mamouneyya Thanks to @gotokatsuya , you won't see that anymore 👍 
Thanks a lot @gotokatsuya 💯
