### ISSUE TITLE
Camera first tab

### ISSUE THREAD

**Issue by resand** [ytakzk/Fusuma#82]
as enabled by default camera tab to display first?

**Comment by ghost** [comment]
i don't think so , but I successfully change the first mode  to camera   by adding this line 
in FusumaViewController at the end off viewDidLoad  
  changeMode(Mode.Camera)

**Comment by ytakzk** [comment]
@resand Yes, as @trollblocks said, you can change the first tab to display by changeMode(Mode.Camera). However, you cannot change the order yet.
