### ISSUE TITLE
Small fix for Swift2.3

### ISSUE THREAD

**Issue by glancashire** [ytakzk/Fusuma#83]
First thanks for your work.

To fix compilation for Swift 2.3.

Please add a ! in the line 220 of FSCameraView.swift

 let imageRef = CGImageCreateWithImageInRect(image.CGImage!, CGRect(x: rcy-iw*0.5, y: 0 , width: iw, height: iw))

Thanks
Graham

**Comment by ytakzk** [comment]
@glancashire Thanks but we no longer support Swift2.3 for Fusuma 🙇
