### ISSUE TITLE
swift 3 error -  Cannot assign value of type 'PHFetchResult<PHAsset>' to type 'PHFetchResult<AnyObject>!'

### ISSUE THREAD

**Issue by billionbucks** [ytakzk/Fusuma#86]
i just update my Xcode to Xcode8 and now i have some errors in `FSalbumView` Class on line no. 89  it says 

 `images = PHAsset.fetchAssets(with: .image, options: options)`
`error - Cannot assign value of type 'PHFetchResult<PHAsset>' to type 'PHFetchResult<AnyObject>!'`

and on line 310 

  `self.images = collectionChanges!.fetchResultAfterChanges`
`error - Cannot assign value of type 'PHFetchResult<PHObject>' to type 'PHFetchResult<AnyObject>!'`

how can i fix it ?

**Comment by Ferrick90** [comment]
Hi @billionbucks , how to fix:
in FSAlbumView Class on line no. 89 and line no. 310

change line no. 28 to `var images: PHFetchResult<PHAsset>!`

or u can try to this code in cocoapods to install Fusuma(Swift 3 version).

pod 'Fusuma', :git => 'https://github.com/pruthvikar/Fusuma.git', :commit => '503865a'

**Comment by steven1mcmurray** [comment]
Thanks @Ferrick90 but it seems this fix above only fixes the break on line 89, not 310. 

Setting line 28 to PHAsset throws error at 310 where it is expecting a "PHObject". Any insights on how to fix? I am also getting an "Ambiguous use of enumerate" error. Pulled latest branch, had to convert to new Swift syntax, still not working.
