### ISSUE TITLE
Crash after updating to iOS 10 , swift 3 

### ISSUE THREAD

**Issue by billionbucks** [ytakzk/Fusuma#89]
after updating to iOS 10 and swift3 when i opened gallery from fusuma\* , application got crashed without any log message the only message i got is this : `(lldb)` and its pointing to - `->  0x185cbcd74 <+8>:  b.lo   0x185cbcd8c               ; <+32>` how can we fix this ??

**Comment by Ferrick90** [comment]
@billionbucks what is ur devices? my device (iPhone 5 iOS9.5) looks OK.

**Comment by billionbucks** [comment]
iPhone5s iOS 10

**Comment by DerkBusser** [comment]
libsystem_kernel.dylib`__pthread_kill:
    0x108ab4efc <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x108ab4f01 <+5>:  movq   %rcx, %r10
    0x108ab4f04 <+8>:  syscall 
->  0x108ab4f06 <+10>: jae    0x108ab4f10               ; <+20>
    0x108ab4f08 <+12>: movq   %rax, %rdi
    0x108ab4f0b <+15>: jmp    0x108aaf7cd               ; cerror_nocancel
    0x108ab4f10 <+20>: retq  
    0x108ab4f11 <+21>: nop  
    0x108ab4f12 <+22>: nop  
    0x108ab4f13 <+23>: nop

**Comment by luisgizirian** [comment]
Couldn't find the Apple link that describes this change at IOS 10, but
here's a Stack Exchange answer on that matter:
http://stackoverflow.com/questions/38643179/crash-requesting-authorisation-to-photos-library-in-ios-10

**Comment by the-freshlord** [comment]
Did you make sure to add the permission of accessing the camera and library? If these are specified in your Info.plist file, your app will crash.

**Comment by whlsxl** [comment]
ADD `NSPhotoLibraryUsageDescription` & `NSCameraUsageDescription` in info.plist will solve this crash.
PLS add this two items on the example~

**Comment by Ferrick90** [comment]
hey, someone can help me to test the [PR](https://github.com/ytakzk/Fusuma/pull/93) whether able to fix the crash or not.

**Comment by whlsxl** [comment]
@Ferrick90 that not fix this issue, should add this two description at Example's info.plist

**Comment by Ferrick90** [comment]
thanks @whlsxl . I have updated the Example's info plist too.

**Comment by ytakzk** [comment]
@billionbucks The latest version has the code fix for this. Thanks!
