### ISSUE TITLE
Way to know the image returned from dismiss: or selected: is taking by the camera or chosen from camera roll?

### ISSUE THREAD

**Issue by realq86** [ytakzk/Fusuma#91]
I noticed photos taken by the camera inside Fusuma isn't saved to the camera roll automatically.  I'd like to save it but noticed there is not a great place to put that line of code.

If simply put the saving code in dismiss photos chosen from the camera roll will also be saved making 2 copies in the camera roll.

The parameter from both delegates are just UIImage without any indication where was the last source.

**Comment by andreyrd** [comment]
I fixed this locally by giving FusumaViewController.mode public access level #97

Then I just check the mode when in the delegate. I'd like to see a solution to be added to the library, though, because it's a little annoying to have to go in and make the changes every time the library updates.
