### ISSUE TITLE
done (select image bar button) is not visible sometimes

### ISSUE THREAD

**Issue by billionbucks** [ytakzk/Fusuma#95]
as title says that bar button is not visible , how can i fix it ? it shows up once i switch form camera roll to camera tab.

**Comment by nkezhaya** [comment]
+1

**Comment by sebayaki** [comment]
+1.
When it first asks the permissions, and user clicks "Allow"
the Check button is not visible on the top right side.

**Comment by nkezhaya** [comment]
@sydneyitguy I believe this has been fixed by a pull request that is already merged into `master`.

**Comment by sebayaki** [comment]
@whitepaperclip Yep I just saw that commit. Thanks for letting me know.

**Comment by nkezhaya** [comment]
@ytakzk Close this out?
