### ISSUE TITLE
Opening .xib files in Xcode 8.0 breaks views.

### ISSUE THREAD

**Issue by econner** [ytakzk/Fusuma#96]
Just curious if anyone has encountered this issue.

When I open any of the .xib files in Xcode 8 I am prompted to select an initial view:
![image](https://cloud.githubusercontent.com/assets/527947/19015199/e5ec4bae-87b4-11e6-9dc3-947caf5306c9.png)

If I do this, the nib produces a bunch of misplacement "view will be different at runtime" errors:
<img width="650" alt="screen shot 2016-10-01 at 8 57 49 am" src="https://cloud.githubusercontent.com/assets/527947/19015225/4f185e38-87b5-11e6-81bb-86efe135b4cf.png">

If I then "Fix Misplacement" on these views when I run the app the camera and photo views become too large and break the rest of the view:
<img width="378" alt="screen shot 2016-10-01 at 8 58 33 am" src="https://cloud.githubusercontent.com/assets/527947/19015241/866184b4-87b5-11e6-81de-ffa983a2997f.png">
<img width="382" alt="screen shot 2016-10-01 at 8 58 24 am" src="https://cloud.githubusercontent.com/assets/527947/19015242/867c2b8e-87b5-11e6-9296-0a6f1a0e434e.png">

I would love to help out with a fix, but I'm confused as to why this happens.  I was under the impression that fixing the misplacement would just update in the nib whatever the app would show at runtime and shouldn't affect the actual layout.

Has anyone encountered the same issue?

Thanks

**Comment by dariuxmx** [comment]
Try to resize the views, check this screenshot. Or maybe try to update the constraints.
<img width="482" alt="screen shot 2016-10-02 at 7 11 34 pm" src="https://cloud.githubusercontent.com/assets/6062429/19025251/b01dfcfc-88db-11e6-86d8-5217e6ca5e7c.png">

**Comment by meirinberg** [comment]
@econner I am having the same issue... Did you find the solution?
