### ISSUE TITLE
Remove class final declaration

### ISSUE THREAD

**Issue by wokelchords** [ytakzk/Fusuma#98]
Can you remove the final declaration for the FusumaViewController class so that we can extend from it?

**Comment by ytakzk** [comment]
@sfkewong do you still need to extend this library as you want?

**Comment by diegoperini** [comment]
Yes please. I want to be able to edit title styling (fonts, colors, icons etc) as well as add extra padding for status bar consideration. It seems very easy to do so by overriding `viewDidLoad()`.
